export enum ActionTypes {
  UPDATE_AUTH_DETAILS = 'UPDATE_AUTH_DETAILS',
  CLEAR_AUTH_DETAILS = 'CLEAR_AUTH_DETAILS'
  // USED JUST AS A STRING VALUE, DECLARING HERE SO IT WILL BE EASY TO CHANGE LATER
}
