export enum ActionTypes {
  FETCH_ENTRIES = 'FETCH_ENTRIES',
  FILTER_PROJECT = 'FILTER_PROJECT',
  FILTER_PHASE = 'FILTER_PHASE',
  FILTER_USER = 'FILTER_USER',
  // USED JUST AS A STRING VALUE, DECLARING HERE SO IT WILL BE EASY TO CHANGE LATER
}
