export enum ActionTypes {
  FETCH_ENTRIES = 'FETCH_ENTRIES',
  UPDATE_FILTER = 'UPDATE_FILTER',
  CLEAR_ENTRIES = 'CLEAR_ENTRIES',

  // USED JUST AS A STRING VALUE, DECLARING HERE SO IT WILL BE EASY TO CHANGE LATER
}
